# Generated by Django 5.0.3 on 2024-03-20 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 20, 8, 2, 668660), verbose_name='Дата производства'),
        ),
    ]
