# Generated by Django 5.0.3 on 2024-04-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_blogarticle_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogArticle',
        ),
    ]
