# Generated by Django 5.0.3 on 2024-03-20 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_manufactured_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 17, 9, 24, 759869, tzinfo=datetime.timezone.utc), verbose_name='Дата производства'),
        ),
    ]
