# Generated by Django 5.0.3 on 2024-03-20 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_manufactured_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата производства'),
        ),
    ]
